# Generated by Django 3.2.12 on 2022-04-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220405_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post_code',
        ),
    ]
