# Generated by Django 3.2.12 on 2022-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_city_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
