# Generated by Django 3.2.12 on 2022-04-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='saves',
        ),
    ]
